apiVersion: v1
kind: PersistentVolume
metadata:
  name: fireeventsource-storage
spec:
  capacity:
    storage: 400Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: fireeventsource-storage
  local:
    path: /data/firedata
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - fireplace-worker

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fireeventsource-storage-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 400Mi
  storageClassName: fireeventsource-storage

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fire-event-source
  labels:
    app: fire-event-source
spec:
  serviceName: "fire-event-source"
  replicas: 1
  selector:
    matchLabels:
      app: fire-event-source
  template:
    metadata:
      labels:
        app: fire-event-source
    spec:
      resources:
        requests:
          cpu: "250m"
          memory: "512Mi"
        limits:
          cpu: "500m"
          memory: "1Gi"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - fireplace-worker
      containers:
      - name: fire-event-source
        image: base:latest
        command: ["/bin/sh", "-c", "python -m src.services.fire_event_source"]
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
        - name: REDIS_PASSWORD
          value: ""
        - name: ON_FAILURE
          value: "raise"
        - name: DATE_FORMAT
          value: "%Y/%m/%d"
        - name: DATETIME_FORMAT
          value: "%Y/%m/%d %H:%M:%S"
        - name: START_DATE
          value: "2010/01/01" 
        - name: BATCH_SIZE
          value: "10000"
        - name: MAIN_LOOP
          value: "True"  
        - name: MAIN_LOOP_INTERVAL
          value: "5"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "fireplace-kafka-kafka-bootstrap:9092"
        - name: RESTART
          value: "False"
        - name: LOG_LEVEL
          value: "INFO"
        - name: FIRE_EVENT_SOURCE_TOPIC
          value: "fire_event_source"
          
        volumeMounts:
        - name: fireeventsource-storage
          mountPath: /data/fire_events
      volumes:
      - name: fireeventsource-storage
        persistentVolumeClaim:
          claimName: fireeventsource-storage-pvc
      restartPolicy: Always
