apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fire-event-data-serving
  labels:
    app: fire-event-data-serving
spec:
  serviceName: "fire-event-data-serving"
  replicas: 1
  selector:
    matchLabels:
      app: fire-event-data-serving
  template:
    metadata:
      labels:
        app: fire-event-data-serving
    spec:
      resources:
        requests:
          cpu: "250m"
          memory: "512Mi"
        limits:
          cpu: "500m"
          memory: "1Gi"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - fireplace-worker2
      containers:
      - name: fire-event-data-serving
        image: base:latest
        command: ["/bin/sh", "-c", "python -m src.services.fire_event_data_serving"]
        env:
       
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "fireplace-kafka-kafka-bootstrap:9092"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
        - name: REDIS_PASSWORD
          value: ""
        - name: ON_FAILURE
          value: "raise"
        - name: ON_DUPLICATE
          value: "version" # version,replace,continue,fail
        - name: DATE_FORMAT
          value: "%Y/%m/%d"
        - name: DATETIME_FORMAT
          value: "%Y/%m/%d %H:%M:%S|%Y/%m/%d %I:%M:%S %p"
        - name: BATCH_SIZE
          value: "10"
        - name: MAIN_LOOP
          value: "True"  
        - name: MAIN_LOOP_INTERVAL
          value: "10"
        - name: RESTART
          value: "False"
        - name: LOG_LEVEL
          value: "INFO"
        - name: LOG_LEVEL_MAPPINGS
          value: "fire_event_data_serving:DEBUG,logger_utils:DEBUG"
        - name: EVENTS_SOURCE_TOPIC
          value: "fire_event_source"
        
     
      restartPolicy: Always
