apiVersion: batch/v1
kind: Job
metadata:
  name: simple-counting
  labels:
    app: example
spec:
  template:
    metadata:
      labels:
        app: example
    spec:
      restartPolicy: Never
      containers:
      - name: simple-counting-container
        image: base:latest
        command: ["/bin/sh", "-c", "python -m src.analysis.simple_counting"]
        env: 
          - name: REDIS_HOST
            value: "redis"
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_DB
            value: "0"
          - name: REDIS_PASSWORD
            value: ""
          - name: LOG_LEVEL
            value: "INFO"
          - name: LOG_LEVEL_MAPPINGS
            value: "simple_counting:DEBUG"